name: air_generator_example
description: An example of how to use air_generator.
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  air_generator:
    path: ..

dev_dependencies:
  build_runner: ^2.4.0
